### ISSUE TITLE
Why is Ratio.FloatConversion.float_to_rational/2 inaccurate?

### ISSUE THREAD

**Issue by mat-hek** [Qqwy/elixir-rational#26]
I'm unable to understand [the docs](https://hexdocs.pm/ratio/2.2.2/Ratio.FloatConversion.html#float_to_rational/2) for that function. Could you please explain why is there any precision loss and base-10 encoding involved there? AFAIK all float numbers are rational by definition, so conversion shouldn't introduce any error.

**Comment by Qqwy** [comment]
Great question!

The difference is between what value you _as human_ think you have, and what value is actually stored in the bits of the float. 

As an example: 
```
iex> :erlang.float_to_list(0.02)
'2.00000000000000004163e-02'
```
_(`:erlang.float_to_list` is used under the hood by `float_to_rational`)_.

The reason that this is the default behaviour of this function is because this is most commonly in line with what application writers want (and also e.g. what you see when when inspecting a float in the Elixir console). Compare it with for intance:

```
iex> :erlang.float_to_list(0.2, [{:decimals, 10}, :compact])
'2.0'
```

So that's where the difference stems from.

If however you require a rational number that is closer to the value _actually_ stored in the float, then you can increase the `max_decimals` value.

---

I do agree with you that the documentation might be made more clear. However, I am not entirely sure what to add. Possibly because I am too close to the subject matter at hand, which makes it sometimes difficult to (concisely) explain something. Any suggestions? :slightly_smiling_face:

**Comment by mat-hek** [comment]
Ok, now I see what you aim to achieve here, but IMHO there are better ways to do this, for example [this one](https://stackoverflow.com/a/450513/2411220). It's not bound to base-10 numbers, doesn't involve calling `float_to_list` and can be more easily explained. Moreover, this way you can provide 'accuracy level' that introduces no error, making `float_number |> Ratio.new() |> Ratio.to_float() == float_number` always satisfied.

**Comment by Qqwy** [comment]
I've been thinking a little about this during these last few days. 
At first I thought that it was not a very good idea because when someone writes `Ratio.new(0.2)` then it would be nice if that became `1 <|> 5` automatically.

However, I have since realized that this is not a very strong argument. Rather, when people are writing hard-coded values in their source code anyway, they could just as easily write `1 <|> 5` or `Ratio.new(1, 5)` (or even e.g. `Ratio.new(2, 10)`) directly.

So: I am all for this: 

- Let's make `Ratio.new(some_float)` and `Ratio.to_float()` each other's proper inverses.
- `Ratio.FloatConversion.float_to_rational`'s implementation will be unchanged.
  - It's documentation should however be improved, detailing when to use `Ratio.new` vs `float_to_rational`.

I myself unfortunately only have time to work on this after the holidays. If you would like to help out and write a PR for it, then that would be be faster and much appreciated! :smile:

**Comment by Qqwy** [comment]
For posterity/clarity: I've asked on the Elixir forum about inspecting the internal structure of floats on the BEAM, to help with implementing this. https://elixirforum.com/t/erlang-how-to-see-a-float-in-its-actual-bitwise-representation/27942

**Comment by mat-hek** [comment]
I have been digging into the topic for a while and found out that there's a good compromise between having reasonable denominator and 100% accuracy. What we're actually looking for is the rational with the smallest denominator that converted back to float is equal to the float given as input. Thus, the rational we want lies within `[f - e/2, f + e/2)`, where f is the float and e is the representation precision. I found an algorithm doing exactly that - it's described [here](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.303.867&rep=rep1&type=pdf), along with some research. When I have some time again I'll try to understand and implement that.

**Comment by Qqwy** [comment]
@mat-hek pretty-printing floats is a very different problem. I recently saw a very interesting [talk](https://www.youtube.com/watch?v=kw-U6smcLzk) about [ryu](https://github.com/ulfjack/ryu) which is a super clever (and super difficult to understand :sweat_smile: ) algorithm/implementation to do this.

The paper you link to seems interesting, but I think for now this is out of scope for the `Ratio` library. You convinced me before that converting to a rational number with a high denominator that matches the builtin float precision is the way to go forward since this is more useful for the common case of usage.

**Comment by Qqwy** [comment]
I have been looking into it in more detail.

[Here](https://github.com/ericmj/decimal/blob/v1.8.1/lib/decimal.ex#L1299) is what Decimal does:

```elixir
  def from_float(float) when is_float(float) do
    float
    |> :io_lib_format.fwrite_g()
    |> fix_float_exp()
    |> IO.iodata_to_binary()
    |> new()
  end
```

Interesting here is that they go for the readable representation of the float rather than the precise (for some definition of precise) implementation.

On the other hand, the easiest way to make the floating-to-rational conversion 'precise' is to just keep using the `      :erlang.float_to_list(float, [{:decimals, max_decimals}, :compact])` but with `max_decimals` set to 249 (which is the largest value the Erlang runtime will accept).

This will result in e.g.

```
iex>       :erlang.float_to_list(1.0 / 3, [{:decimals, 249}, :compact])
'0.333333333333333314829616256247390992939472198486328125'
```
which is probably as precise as one could want floats to be.


So after a long time of thinking, changing the default configuration value is the only required change :blush: .

**Comment by Qqwy** [comment]
This issue is superseded by #46. Thanks to @kipcole9 I am now aware that `Float.ratio/1` exists which already does the required super-precise conversion for us in a much cleaner (and probably faster) way.
