### ISSUE TITLE
troubles with Ratio.floor

### ISSUE THREAD

**Issue by skilchen** [Qqwy/elixir-rational#7]
First of all: thanks a lot for this nice and very useful module!

In elixir 1.7 there is a conflict between Ratio.floor/1 and Kernel.floor/1. Probably`floor/1` needs to be added to the `except` clause in `import Kernel`.

But the implementation of Ratio.floor is buggy for negative Rationals. The used Kernel.div truncates towards zero, but floor should truncate towards negative infinity. `Ratio.floor(Ratio.new(-3, 2))` should return -2 and not -1 according to the usual definition of `floor`:
> Returns the largest integer not greater than number

You probably should use `Integer.floor_div` in your floor implementation (instead of `Kernel.div`)

**Comment by Qqwy** [comment]
Thank you very much for your issue report! I am just back from vacation, which is why I was not able to get back to you sooner.

The first issue definitely is a conflict because of the new Elixir version, and your proposed fix is the correct one.
I will investigate the second issue, about the implementation of `floor` in more detail, just to make sure.

Regardless of outcome, `Ratio.floor` needs some documentation on the choice of truncation towards negative infinity or truncation towards zero.

Expect a PR and a new version release this evening or tomorrow morning :-).

**Comment by Qqwy** [comment]
New version has been published!

If there are still problems, please open up a new issue :-)

**Comment by skilchen** [comment]
Thank you!

**Comment by skilchen** [comment]
Minor nitpick about your new doc comments for `floor` and `ceil`:
As far as I understand `floor` always rounds towards negative infinity, and `ceil` rounds always towards positive infinity. There is nothing special about negative numbers.
